[General]

# ======= 注释 ======= #
# > Shadowrocket打开HTTPS解密方法：
# > 1 点击配置文件ⓘ - HTTPS解密 - 证书 - 生成新的CA证书 - 安装证书
# > 2 手机设置 - 已下载描述文件 - 安装
# > 3 手机设置 - 通用 - 关于本机 - 证书信任设置 - 开启对应Shadowrocket证书信任

# ======= 手动 ======= #
# > 请在「设置」-「GeoLite2资料库」-「国家」-「URL」填写下面链接
# https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb

# ======= 通用 ======= #

# 旁路系统
bypass-system = true

# 自动回复
icmp-auto-reply = true

# 接管模式
compatibility-mode=3

# 启用IPv6
ipv6 = ture

# 首选IPv6
prefer-ipv6 = ture

# 私有IP应答
private-ip-answer = true

# 始终真实IP
always-real-ip = *.lan

# DNS直连系统
dns-direct-system = false

# DNS回退系统
dns-fallback-system = false

# UDP回退策略
udp-policy-not-supported-behaviour = REJECT

# TUN排除路由
tun-excluded-routes = 10.0.0.0/8, 127.0.0.0/8, 192.168.0.0/16

# 常规DNS服务器
dns-server = https://doh.pub/dns-query, https://dns.alidns.com/dns-query

# 回退DNS服务器
fallback-dns-server = 223.5.5.5, 119.29.29.29

# 直连回退代理
dns-direct-fallback-proxy = true

# 始终拒绝重写
always-reject-url-rewrite = false

[Proxy Group]

# ======= 手动 ======= #
全球加速 = select,香港节点,台湾节点,日本节点,狮城节点,美国节点,interval=86400,timeout=5,select=0,url=http://www.gstatic.com/generate_204
苹果服务 = select,DIRECT,自动选择,香港节点,台湾节点,狮城节点,日本节点,美国节点,interval=86400,timeout=5,select=0,url=http://www.gstatic.com/generate_204
智能助手 = select,美国节点,自动选择,interval=86400,timeout=5,select=0,url=http://www.gstatic.com/generate_204
兜底分流 = select,自动选择,DIRECT,interval=86400,timeout=5,select=2,url=http://www.gstatic.com/generate_204

# ======= 自动 ======= #
# 自动选择
自动选择 = url-test,url=http://www.gstatic.com/generate_204,interval=1800,tolerance=50,timeout=5,select=0,policy-regex-filter=^
# 香港节点
香港节点 = url-test,url=http://www.gstatic.com/generate_204,interval=1800,tolerance=50,timeout=5,select=0,policy-regex-filter=香港|港|HK|🇭🇰|(?i)Hong
# 台湾节点
台湾节点 = url-test,url=http://www.gstatic.com/generate_204,interval=1800,tolerance=50,timeout=5,select=0,policy-regex-filter=台湾|台|TW|🇹🇼|(?i)Taiwan
# 日本节点
日本节点 = url-test,url=http://www.gstatic.com/generate_204,interval=1800,tolerance=50,timeout=5,select=0,policy-regex-filter=日本|日|JP|🇯🇵|(?i)Japan
# 韩国节点
韩国节点 = url-test,url=http://www.gstatic.com/generate_204,interval=1800,tolerance=50,timeout=5,select=0,policy-regex-filter=韩国|韩|KR|🇰🇷|(?i)Korea
# 狮城节点
狮城节点 = url-test,url=http://www.gstatic.com/generate_204,interval=1800,tolerance=50,timeout=5,select=0,policy-regex-filter=新加坡|狮|SG|🇸🇬|(?i)Singapore
# 美国节点
美国节点 = url-test,url=http://www.gstatic.com/generate_204,interval=1800,tolerance=50,timeout=5,select=0,policy-regex-filter=美国|美|US|🇺🇸|(?i)States

[Rule]

# ======= 分流 ======= #
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/Unbreak.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/AI.list,智能助手
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/Apple.list,苹果服务
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/CNMedia.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/Scholar.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/Global.list,全球加速
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/LAN.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/3S-AC/Loon/refs/heads/main/Rule/GEOIPCN.list,DIRECT
FINAL,兜底分流

[MITM]
# HTTPS解密
enable = false

# 主机名
hostname = -buy.itunes.apple.com
